CREATE TABLE public.refresh_tokens (
                                       id BIGINT PRIMARY KEY,
                                       expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                       token VARCHAR(255) NOT NULL UNIQUE,
                                       user_id BIGINT NOT NULL,
                                       CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

ALTER TABLE public.refresh_tokens
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.refresh_tokens_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

